baseURL: "https://dipankarsrirag.github.io/" 
title: Dipankar Srirag
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: About Me
        #   url: about/
        #   weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: CV
          url: cv.pdf
          weight: 5

params:
    description: "Welcome to Dipankar's website. Dipankar is an NLP researcher working at UNSW Sydney."
    author: Dipankar Srirag
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dipankar Srirag
          subtitle: |
            <p>Hello, this is Dipankar! 🦘</p>
            <br>
            <p>I am a researcher at the <b><a href="https://unswnlp.github.io/">UNSW-NLP group</a></b> at <b><a href="https://www.unsw.edu.au/">University of New South Wales</a></b>. My research interests broadly lie in socio-culturally inclusive language technologies. </p>
            <br>
            <p>I graduated with a Master of Information Technology with Excellence from UNSW Sydney. My masters thesis, supervised by <b><a href="https://www.unsw.edu.au/staff/aditya-joshi/">Dr. Aditya Joshi</a></b>, involved evaluating and improving dialect robustness for decoder models using adapter-based methods.</p>
            <br>
            <p>Don't hesitate to reach out if you're interested in connecting, collaborating or discussing research... and beyond! I am easier to find on Twitter/X. </p>

          imageUrl: "profile.png"
          imageWidth: 240
          imageHeight: 300
          buttons:
            # - name: About Me
            #   url: about/
            - name: Papers
              url: papers/
            - name: Teaching
              url: courses/
            - name: Data
              url: data/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            - name: CV
              url: cv.pdf

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:d.srirag@unsw.edu.au
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=8dUrhxwAAAAJ
        - name: GitHub
          url: https://github.com/dipankarsrirag
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/dipankarsrirag
        - name: Bluesky
          url: https://bsky.app/profile/dipankarsrirag.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dipankar Srirag"
      icon: favicon.ico
      iconHeight: 24

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2